<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-20T18:42:08 IST" name="Suite" finished-at="2024-12-20T18:42:27 IST" duration-ms="18801">
    <groups>
      <group name="error">
        <method signature="StandAloneTestWithPageObjectsErrorMessage.itemValidation2()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" name="itemValidation2" class="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage"/>
        <method signature="StandAloneTestWithPageObjectsErrorMessage.loginValidation()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" name="loginValidation" class="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage"/>
      </group> <!-- error -->
    </groups>
    <test started-at="2024-12-20T18:42:08 IST" name="Main Test" finished-at="2024-12-20T18:42:08 IST" duration-ms="8">
    </test> <!-- Main Test -->
    <test started-at="2024-12-20T18:42:08 IST" name="Error Test" finished-at="2024-12-20T18:42:27 IST" duration-ms="18733">
      <class name="stanalone.tests.StandAloneTestWithPageObjectsErrorMessage">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:08 IST" name="launchApplication" finished-at="2024-12-20T18:42:10 IST" duration-ms="2447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="itemValidation2()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:10 IST" name="itemValidation2" finished-at="2024-12-20T18:42:24 IST" duration-ms="13590" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ZARA COAT 3] but found [IPHONE 13  PRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ZARA COAT 3] but found [IPHONE 13  PRO]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stanalone.tests.StandAloneTestWithPageObjectsErrorMessage.itemValidation2(StandAloneTestWithPageObjectsErrorMessage.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- itemValidation2 -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:24 IST" name="closeBrowser" finished-at="2024-12-20T18:42:24 IST" duration-ms="188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:24 IST" name="launchApplication" finished-at="2024-12-20T18:42:26 IST" duration-ms="1846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginValidation()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:26 IST" name="loginValidation" finished-at="2024-12-20T18:42:26 IST" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:stanalone.tests.StandAloneTestWithPageObjectsErrorMessage@48f2bd5b]" started-at="2024-12-20T18:42:26 IST" name="closeBrowser" finished-at="2024-12-20T18:42:27 IST" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- stanalone.tests.StandAloneTestWithPageObjectsErrorMessage -->
    </test> <!-- Error Test -->
  </suite> <!-- Suite -->
</testng-results>
